name: flutterpokemon
description: A Flutter app that queries the Pokemon API

version: 1.2.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  http:
  transparent_image:
  provider:
  shared_preferences:
  url_launcher:
dev_dependencies:
  flutter_launcher_icons: "^0.7.0"
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/pokeball.png"
  image_path_android: "assets/launcher/pokeball.png"
  adaptive_icon_foreground: "assets/launcher/pokeball.png"